### ISSUE TITLE
Questions

### ISSUE THREAD

**Issue by GeorgeFive** [duck7000/Discogs#1]
Hey there! I've been thinking about adding music stuff into my project for a while now, and just noticed that you have this going on. I haven't installed this or played with it at all, as I'm still debating the pros and cons of going in this direction, but I'm curious...

1) Are you still maintaining this project? I'm already familiar with the IMDb code and the way you do things, so this should be pretty simple to work with... just wanted to make sure this was still working / active.

2) One thing that bugs me about discogs themselves, is the way they only show release year on the master release. I'd much rather have the exact date. I know you can dig into the releases under the master and usually find the data you're looking for, but that seems like it would be a pain in the long run. Does your code have any nice, easy way of handling this?

**Comment by duck7000** [comment]
@GeorgeFive 

I'm surprised, you are the first that ever responded to this hah

1e Well yes this is something i still maintain, but it is scraper not an API. I use this for my cd collection app to add information about specific cd's.
I haven't use it for a while so there may be a problem with it. I suggest to check it out, and if you have questions about how it works let me know. There isn't much documentation i admit.

2e Short answer: no I only use the release year for that specific cd that i have. I want to search on barcode so that i get specific info, discogss provide that ability

**Comment by duck7000** [comment]
i did a quick test and it still seems to work.

You do need to know that discoggs does has their own API so you might go that route.
I didn't go that route because they require all kinds of authentification methods that i don't know/don't have. So scraping like this was the easy way out i guess.

**Comment by GeorgeFive** [comment]
I'm in the same boat with you there, I don't have any of those authentication methods either. I also looked at their code examples, and everything seems horribly out of date.... I saw your stuff was last updated five months ago, so it seemed more up to date.

Still not even sure I want to go down this road in my project, but I've been toying with the idea for a while. I used to run a music-based site with pretty much every album release ever available, and I still have that data dump.... but I shut the site down years ago, so I know it would be incredibly outdated with all of the new releases since then.

I dunno, guess I'm mainly thinking out loud here, haha.

**Comment by duck7000** [comment]
Well start playing with my scraper and decide if that is what you want?

I can't make any promises but if you start using it i will try maintain it to keep it working. That shouldn't be  too hard as their html is pretty simple.
And suggestions about adding stuff are always considered.

**Comment by duck7000** [comment]
@GeorgeFive 
This isn't working anymore, at least not for me, they block every request i try.
So save to say discogs scraper is dead, sorry.

I'm currently starting to work something similar with musicbrainz. They don't block (jet)..
At the moment i started to get the search going but this is much more work/complicated as i thought.

**Comment by GeorgeFive** [comment]
musicbrainz does have a free API, I originally thought of using this.  Looks pretty simple and full featured.

**Comment by duck7000** [comment]
Oh i might try their API, didn't know they had one

**Comment by GeorgeFive** [comment]
Yep!  https://musicbrainz.org/doc/MusicBrainz_API

**Comment by duck7000** [comment]
Ah thanks, it looks doable although the php librarys that are available are overly complicated.
For simple searches and lookups with a mbid (musicbrainz id) it might be a solution.

I'll try

**Comment by GeorgeFive** [comment]
They do allow lookup by title as well:  https://musicbrainz.org/doc/MusicBrainz_API/Search

http://musicbrainz.org/ws/2/artist/?query=artist:the%20beatles

**Comment by duck7000** [comment]
yes i have read a few pages, it is a lot of text but basically doable.

I might just use imdbphp6 as base, it is already API based so converting this to use musicbrainz should be possible.

It might be a project for next winter though

**Comment by GeorgeFive** [comment]
I keep toying with the idea of integrating music stuff into my site, but I haven't pulled the trigger yet.  Maybe by then I will have decided, haha.

**Comment by duck7000** [comment]
hahaha it is a toy project for me too

**Comment by duck7000** [comment]
@GeorgeFive 
In the meantime i have the search partly working (not even close finished) but i was wondering if the cache system is necessary in musicBrainz? I don't use it and the requests are free (as long as there is max 1 request per second, otherwise you will get blocked)
I'm only going to use it to get info for a specific cd that i own and want to add it in my program.

I would like to keep this as simple as possible, what is your view on this?

Edit: currently searching on barcode and cd title are supported, Search can be limited between 1 and 100.
Search can be limited to (default) CD (case insensitive) but can be set in config to others like vinyl

**Comment by GeorgeFive** [comment]
I don't think caching is really needed here... maybe later if needed, it's hard to say without using the code and seeing how it performs.

Will you have search by artist available?

Any internal throttling, or should that be up to the user?  My end goal for this would be to type in an artist, see a list of their albums (maybe separated by type - LP, EP, compilation, live, box set, etc), checkmarks or something to add the ones I want, click add, bam.... get info for all of them and add it to my db.  I'm thinking, if I were to add 10 albums at once like this, that would go over their limit and might cause a ban?

**Comment by duck7000** [comment]
Here is some info about throttling
https://musicbrainz.org/doc/MusicBrainz_API/Rate_Limiting

Search by artist can be added later, or use the text search.
If you search for a artist (say AC/DC) there will be max 100 results so impossible to get all albums i guess (musicBrainz api has a max results of 100)

So my goal and yours differ quite a lot, you might be better of with a php library that handles things you want?
https://musicbrainz.org/doc/MusicBrainz_API#Libraries
I don't want to use them, too complicated for my goal but it might be what you want

**Comment by GeorgeFive** [comment]
Sounds good.  I may check your version out when it's released, just to see.  My long-term goal is pretty simple - get the basic album data for all albums from a given artist, quick and easy.  Not concerned with all of the different versions, just the standard, basic versions.

Still up in the air, so who knows what will happen, hah.

**Comment by duck7000** [comment]
@GeorgeFive 

I made a new repo for musicBrainzPHP
It works for my needs but i also added search for artist and artist+title

So check it out, it might not be fully finished but it is a good start as it works.
I opened a new issue in musicBrainzPHP with some details, a wiki page will come as it is finished

**Comment by duck7000** [comment]
And discogsPHP now works again so it might be a temporary block, but musicBrainz is much better and has a free api so i focus on that version and leave discogsPHP as is.
